# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "latest"
  jobs:
    post_create_environment:
      - pip install poetry
      # https://github.com/readthedocs/readthedocs.org/issues/9740
      - poetry config virtualenvs.create false
      - poetry install --with=ci

sphinx:
  configuration: docs/conf.py
