# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "latest"
  jobs:
    pre_install:
      - pip install poetry
      - poetry install --with=ci

sphinx:
  configuration: docs/conf.py
