# :see: https://peps.python.org/pep-0621/

[project]
name = "phx-class-registry"
version = "4.1.0"
description = "Factory+Registry pattern for Python classes"
readme = "README.rst"
requires-python = ">= 3.10"
license = { file = "LICENCE.txt" }
authors = [
    { email = "Phoenix Zerin <phx@phx.nz>" }
]
keywords = [
    "design pattern",
    "factory pattern",
    "registry pattern",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
"build-system" = ["build", "twine"]
"docs-builder" = ["sphinx", "sphinx_rtd_theme"]
"test-runner" = ["tox"]

[project.urls]
Documentation = "https://class-registry.readthedocs.io/"
Changelog = "https://github.com/todofixthis/class-registry/releases"
Issues = "https://github.com/todofixthis/class-registry/issues"
Repository = "https://github.com/todofixthis/class-registry"
