#!/usr/bin/env python3
"""Regenerates docs/adr/INDEX.md from ADR frontmatter, or reports what binds a path.

Run automatically by autohooks on pre-commit when ADR files change.
Run manually: uv run python scripts/adr/generate_index.py

    uv run python scripts/adr/generate_index.py --for src/class_registry/base.py

reports the decisions scoping that path. The hook runs it over the staged paths,
which is the direction INDEX.md cannot serve: the index reaches a reader who already
suspects a decision exists, where this reaches one who does not.
"""

import re
import sys
from pathlib import Path
from typing import Any

import yaml

# Resolved from this file rather than the working directory: a path relative to the
# caller's cwd points at whichever directory they happen to be standing in, and scope
# entries are checked against it. Every function below takes the root explicitly, so
# none can fall back to this file's own repo.
REPO_ROOT = Path(__file__).resolve().parents[2]
ADR_DIR = Path("docs") / "adr"
ADR_INDEX_FILENAME = "INDEX.md"

STATUSES = ("Accepted", "Archived", "Superseded")

# Statuses still in force, and so still worth checking and still worth surfacing to
# whoever is editing a path one of them scopes. Superseded is neither: it is history,
# and "supersede, don't edit" means a stale path in one could not be fixed anyway.
BINDING_STATUSES = ("Accepted", "Archived")

# Kept out of the index an agent loads by default: Superseded because a later ADR
# replaced it, Archived because something other than a reader carries it. Both keep
# their full text in the repo, and an Archived decision is as binding as an Accepted
# one.
HIDDEN_STATUSES = ("Archived", "Superseded")

# Frontmatter each status requires and the others refuse, so a status changed without
# its companion field fails here rather than leaving stale metadata behind.
STATUS_FIELDS = {"Archived": "archived-because", "Superseded": "superseded-by"}

# The revisit trigger and the ADR that spent it. These pair with each other rather
# than with a status: either sits with any status, and a discharge names something to
# spend, so it cannot stand alone.
REVISIT_WHEN_FIELD = "revisit-when"
REVISIT_DISCHARGED_BY_FIELD = "revisit-discharged-by"

# The paths where a breach of a decision would be authored, so it reaches whoever
# edits one of them. Entries are exact file paths or directory prefixes ending in
# `/`, never globs.
SCOPE_FIELD = "scope"

# Replaced by `scope` (see docs/adr/004). Named here so a stale field fails rather
# than being silently ignored, which is what would otherwise let a half-finished
# migration pass in both directions.
TAGS_FIELD = "tags"

INDEX_HEADER = (
    "<!-- Auto-generated by scripts/adr/generate_index.py — do not edit manually. -->\n"
    "\n"
    "# ADR Index\n"
)
TABLE_HEADER = (
    "| # | Status | Title | Scope | Summary | Revisit |\n"
    "|---|--------|-------|-------|---------|---------|\n"
)

# An empty table reads as a file that was truncated. Say so instead.
EMPTY_NOTE = "_No decisions are recorded yet._\n"

RE_ADR_FILENAME = re.compile(r"^\d+-.*\.md$")
RE_FILE_NUMBER = re.compile(r"^(\d+)")
RE_FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
RE_H1_TITLE = re.compile(r"^# (.+)$", re.MULTILINE)
RE_NUMBER_PREFIX = re.compile(r"^\d+:\s*")


def parse_adr(content: str) -> tuple[dict[str, Any], str, list[str]]:
    """Extract (frontmatter, title, problems) from one ADR document.

    Every rule a document must satisfy to be an ADR is checked here rather than
    split with the caller, which then only decides what to do with a file that has
    problems. `problems` is empty only when both other values are complete; on any
    problem, the fields and title carry whatever could still be read, for an error
    message to name.
    """
    match = RE_FRONTMATTER.match(content)
    if not match:
        return {}, "", ["has no frontmatter block"]

    try:
        fields = yaml.safe_load(match.group(1))
    except yaml.YAMLError as error:
        return {}, "", [f"has invalid YAML frontmatter: {error}"]
    if not isinstance(fields, dict):
        return {}, "", ["frontmatter is not a mapping of `key: value` pairs"]

    problems: list[str] = []

    title_match = RE_H1_TITLE.search(match.group(2))
    if title_match:
        title = RE_NUMBER_PREFIX.sub("", title_match.group(1).strip())
    else:
        title = ""
        problems.append("has no level-one title heading")

    status = fields.get("status")
    if status not in STATUSES:
        problems.append(f"has status {status!r}; expected one of {', '.join(STATUSES)}")
    for owner, field in STATUS_FIELDS.items():
        if status == owner and not fields.get(field):
            problems.append(f"is {owner} but declares no `{field}`")
        elif status != owner and fields.get(field):
            problems.append(
                f"declares `{field}` but its status is {status!r}, not {owner}"
            )

    if fields.get(REVISIT_DISCHARGED_BY_FIELD) and not fields.get(REVISIT_WHEN_FIELD):
        problems.append(
            f"declares `{REVISIT_DISCHARGED_BY_FIELD}` but no `{REVISIT_WHEN_FIELD}` to spend"
        )

    if TAGS_FIELD in fields:
        problems.append(
            f"declares `{TAGS_FIELD}`, which `{SCOPE_FIELD}` replaced; name the paths the "
            "decision binds instead of the words someone might search for"
        )

    # Absent and empty are different answers, so the field is required and `[]` says
    # the decision binds no path. An optional field's absence would carry no more
    # than the missing tags it replaced: unfilled and deliberate look identical.
    if SCOPE_FIELD not in fields:
        problems.append(
            f"declares no `{SCOPE_FIELD}`; list the paths it binds, or `[]` where it binds none"
        )
    elif not isinstance(fields[SCOPE_FIELD], list):
        problems.append(
            f"declares `{SCOPE_FIELD}` as a scalar; write it as an inline list, e.g. "
            f"`{SCOPE_FIELD}: [scripts/, CHANGELOG.md]`"
        )

    return fields, title, problems


def scope_problems(entries: list[str], repo_root: Path) -> list[str]:
    """Return a problem per scope entry that no longer names anything on disk.

    Separate from `parse_adr` because this is the one rule needing the filesystem,
    which keeps every other rule checkable against a string alone.
    """
    problems = []
    for entry in entries:
        # A glob is the natural thing to reach for, and the error for one would
        # otherwise be "nothing matches", which reads as a wrong path rather than as
        # syntax that was never supported.
        if any(char in entry for char in "*?["):
            problems.append(
                f"scopes `{entry}`, which reads as a glob; scope takes exact paths and "
                "directory prefixes ending in `/`, nothing else"
            )
            continue
        target = repo_root / entry
        if not target.exists():
            problems.append(
                f"scopes `{entry}`, which nothing matches; correct it, or drop it where "
                "the code it named is gone for good"
            )
        elif target.is_dir() and not entry.endswith("/"):
            problems.append(f"scopes `{entry}`, a directory; write it as `{entry}/`")
    return problems


def scope_matches(entry: str, path: str) -> bool:
    """Whether a scope entry covers a path: the file itself, or anything beneath it."""
    return path == entry or (entry.endswith("/") and path.startswith(entry))


def cell(value: Any) -> str:
    """Render a frontmatter value for a Markdown table cell, escaping pipes."""
    if isinstance(value, list):
        value = ", ".join(value)
    return str(value).replace("|", "\\|")


def generate(adr_dir: Path, repo_root: Path) -> int:
    """Regenerate INDEX.md from ADR frontmatter. Returns 0 on success, 1 on error.

    Neither directory is defaulted: the caller supplies both, so a test that forgot
    its fixture cannot rewrite this repository's own index.
    """
    index_file = adr_dir / ADR_INDEX_FILENAME

    rows = []
    has_errors = False
    for path in sorted(adr_dir.iterdir()):
        # Dot-files are editor and tooling debris, not documents anyone filed here.
        if path.name.startswith(".") or path.name == ADR_INDEX_FILENAME:
            continue
        # The directory holds ADRs and the index, nothing else, so an unrecognised
        # name is either a document misfiled here or an ADR named wrongly — and the
        # second would drop out of the index silently.
        if not RE_ADR_FILENAME.match(path.name):
            print(
                f"Error: {path.name} is neither an ADR nor {ADR_INDEX_FILENAME}; "
                "rename it NNN-slug.md or move it elsewhere under docs/",
                file=sys.stderr,
            )
            has_errors = True
            continue

        fields, title, problems = parse_adr(path.read_text(encoding="utf-8"))
        # Scope is checked for every decision still in force, Archived ones
        # included: they are out of the index but not out of effect, and their
        # paths rot the same way. A Superseded ADR is left alone, since editing one
        # is forbidden.
        if not problems and fields["status"] in BINDING_STATUSES:
            problems = scope_problems(fields[SCOPE_FIELD], repo_root)
        if problems:
            for problem in problems:
                print(f"Error: {path.name} {problem}", file=sys.stderr)
            has_errors = True
            continue
        if fields["status"] in HIDDEN_STATUSES:
            continue

        # A discharged trigger leaves the index the way a Superseded ADR does: the
        # condition is spent, so carrying it costs every reader context for
        # something nobody can act on. The pair stays in the ADR's own frontmatter
        # as the record.
        revisit = (
            ""
            if fields.get(REVISIT_DISCHARGED_BY_FIELD)
            else fields.get(REVISIT_WHEN_FIELD, "")
        )

        # RE_ADR_FILENAME already required a leading number, so this always matches.
        number_match = RE_FILE_NUMBER.match(path.name)
        assert number_match is not None
        number = number_match.group(1)
        rows.append(
            f"| [{number}]({path.name}) | {cell(fields['status'])} "
            f"| {cell(title)} | {cell(fields[SCOPE_FIELD])} "
            f"| {cell(fields.get('summary', ''))} | {cell(revisit)} |\n"
        )

    if has_errors:
        print("Fix the errors above before committing.", file=sys.stderr)
        return 1

    body = TABLE_HEADER + "".join(rows) if rows else EMPTY_NOTE
    index_file.write_text(f"{INDEX_HEADER}\n{body}", encoding="utf-8")
    print(f"Generated {index_file} ({len(rows)} entries)")
    return 0


def relative_to_repo(path: str, repo_root: Path) -> str:
    """Return `path` as the repo-relative form scope entries are written in.

    An absolute path is what an editor or an agent has to hand, and left alone it
    matches no scope entry — so the lookup would answer "nothing binds this file"
    for a file several decisions bind. A confident false negative is worse than an
    error, which is why a path outside the repository raises rather than returning
    nothing.
    """
    candidate = Path(path)
    if not candidate.is_absolute():
        return path
    try:
        return str(candidate.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        raise SystemExit(f"Error: {path} is outside {repo_root.resolve()}")


def report_scoped_to(paths: list[str], adr_dir: Path, repo_root: Path) -> int:
    """Print the binding decisions covering any of `paths`. Always returns 0.

    This is the direction the index cannot serve. A reader scanning INDEX.md has to
    already suspect a decision exists; this answers the question they actually
    hold — which decisions bind the file in front of me — reaching them through the
    work rather than through a search they had to think to run. It reports Archived
    decisions too, which is the whole point of them: in force, out of the index,
    and met at the moment someone edits what they bind.
    """
    subjects = [relative_to_repo(path, repo_root) for path in paths]
    for path in sorted(adr_dir.iterdir()):
        if path.name.startswith(".") or not RE_ADR_FILENAME.match(path.name):
            continue
        fields, title, problems = parse_adr(path.read_text(encoding="utf-8"))
        # Say so rather than skipping: a malformed ADR silently binds nothing, and
        # this is the one place the lookup speaks, so an invisible gap here reads
        # as "no decision covers your change".
        if problems:
            print(
                f"Warning: {path.name} could not be read, so it binds nothing here",
                file=sys.stderr,
            )
            continue
        if fields["status"] not in BINDING_STATUSES:
            continue
        if any(
            scope_matches(entry, subject)
            for entry in fields[SCOPE_FIELD]
            for subject in subjects
        ):
            number_match = RE_FILE_NUMBER.match(path.name)
            assert number_match is not None
            print(
                f"{number_match.group(1)} ({fields['status']}): {title} — docs/adr/{path.name}"
            )
    return 0


def main(argv: list[str], adr_dir: Path, repo_root: Path) -> int:
    """Regenerate the index, or with `--for`, report the decisions binding some paths."""
    if argv[:1] == ["--for"]:
        if len(argv) < 2:
            print("Error: --for needs at least one path", file=sys.stderr)
            return 1
        return report_scoped_to(argv[1:], adr_dir, repo_root)
    if argv:
        print(f"Error: unrecognised arguments {argv}", file=sys.stderr)
        return 1
    return generate(adr_dir, repo_root)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:], REPO_ROOT / ADR_DIR, REPO_ROOT))
