#!/usr/bin/env python3
"""Regenerates docs/adr/INDEX.md from ADR frontmatter.

Run automatically by autohooks on pre-commit when ADR files change.
Run manually: uv run python scripts/adr/generate_index.py
"""

import re
import sys
from pathlib import Path
from typing import Any

import yaml

ADR_DIR = Path("docs/adr")
INDEX_FILE = ADR_DIR / "INDEX.md"

RE_ADR_FILENAME = re.compile(r"^\d+-.*\.md$")
RE_FRONTMATTER = re.compile(r"^---\n([\s\S]+?)\n---\n([\s\S]*)$")
RE_H1_TITLE = re.compile(r"^# (.+)$", re.MULTILINE)
RE_NUMBER_PREFIX = re.compile(r"^\d+:\s*")
RE_FILE_NUMBER = re.compile(r"^(\d+)")


def parse_adr(content: str) -> tuple[dict[str, Any], str] | None:
    """Extract frontmatter dict and H1 title from ADR content.

    Returns None if frontmatter or title is missing.
    """
    match = RE_FRONTMATTER.match(content)
    if not match:
        return None

    fm = yaml.safe_load(match.group(1))
    body = match.group(2)

    title_match = RE_H1_TITLE.search(body)
    if not title_match:
        return None

    title = RE_NUMBER_PREFIX.sub("", title_match.group(1))

    return fm, title


def generate() -> int:
    """Generate INDEX.md from ADR frontmatter.

    Returns:
        0 on success, 1 on error.
    """
    files = sorted(f for f in ADR_DIR.iterdir() if RE_ADR_FILENAME.match(f.name))

    adrs = []
    has_errors = False

    for path in files:
        content = path.read_text(encoding="utf-8")
        parsed = parse_adr(content)

        if not parsed:
            print(
                f"Error: {path.name} is missing frontmatter or a title heading",
                file=sys.stderr,
            )
            has_errors = True
            continue

        fm, title = parsed

        if fm.get("status") == "Superseded":
            continue

        number_match = RE_FILE_NUMBER.match(path.name)
        if not number_match:
            print(f"Error: {path.name} has no leading number", file=sys.stderr)
            has_errors = True
            continue

        adrs.append((path.name, fm, number_match.group(1), title))

    if has_errors:
        print("Fix the errors above before committing.", file=sys.stderr)
        return 1

    rows = [
        f"| [{number}]({filename}) | {fm.get('status', '')} | {title} | "
        f"{', '.join(fm.get('tags', []))} | {fm.get('summary', '')} |"
        for filename, fm, number, title in adrs
    ]

    output = "\n".join(
        [
            "<!-- Auto-generated by scripts/adr/generate_index.py — do not edit manually. -->",
            "",
            "# ADR Index",
            "",
            "| # | Status | Title | Tags | Summary |",
            "|---|--------|-------|------|---------|",
            *rows,
            "",
        ]
    )

    INDEX_FILE.write_text(output, encoding="utf-8")
    print(f"Generated {INDEX_FILE} ({len(adrs)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(generate())
