# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # Note: Use quotes to avoid float cast - especially important if the
          # version number ends with 0!
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run Tests
        run: python -m unittest
